### PR TITLE
Fix possible race condition in events handler

### LINKED ISSUE #38: Possible race condition in the Publish method of events.go
The slice containing registered event handlers is prone to race conditions: [#](https://github.com/enbility/spine-go/blob/06d9bf07e351c268656532a0b8046c79f3797d23/spine/events.go#L90)
It is intended to be guarded with a lock, but the current way that guarding is done appears to not work as intended: [#](https://github.com/enbility/spine-go/blob/06d9bf07e351c268656532a0b8046c79f3797d23/spine/events.go#L76-L79)

### PR DESCRIPTION
**Pull request by AhmedMagdyCoretech**
Fixes [issue #38](https://github.com/enbility/spine-go/issues/38)

### CODE REVIEW

**Comment by DerAndereAndi** [comment]
Hey Ahmed, thanks a lot for finding this issue and providing a fix!

File: spine/events.go [hunk 1]
```diff
@@ -87,7 +87,7 @@ func (r *events) Publish(payload api.EventPayload) {
 	}
 
 	for _, level := range handlerLevels {
-		for _, item := range r.handlers {
+		for _, item := range handler {
```
Comment (DerAndereAndi) [inline spine/events.go:90]: Why do you interate over the structure variable instead of the local variable? If Publish is invoked again, wouldn't this trigger a race condition?
